const MARKETS = [
  // ─── Commodities ───
  {
    id: 'gold',
    name: 'Gold',
    category: 'commodities',
    emoji: '🥇',
    source: 'coingecko',
    sourceId: 'pax-gold',
    description: 'Gold price via PAX Gold token',
    pollInterval: 300,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 'silver',
    name: 'Silver',
    category: 'commodities',
    emoji: '🥈',
    source: 'coingecko',
    sourceId: 'kinesis-silver',
    description: 'Silver price via Kinesis Silver (KAG)',
    pollInterval: 300,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 'wti_oil',
    name: 'WTI Crude Oil',
    category: 'commodities',
    emoji: '🛢️',
    source: 'oilprice',
    sourceId: 'WTI_USD',
    description: 'West Texas Intermediate crude oil',
    pollInterval: 1200,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 'natural_gas',
    name: 'Natural Gas',
    category: 'commodities',
    emoji: '🔥',
    source: 'oilprice',
    sourceId: 'NATURAL_GAS_USD',
    description: 'Natural gas price',
    pollInterval: 1200,
    shieldEligible: true,
    perpEligible: true,
  },

  // ─── Crypto ───
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    category: 'crypto',
    emoji: '₿',
    source: 'coingecko',
    sourceId: 'bitcoin',
    description: 'Bitcoin cryptocurrency',
    pollInterval: 300,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    category: 'crypto',
    emoji: 'Ξ',
    source: 'coingecko',
    sourceId: 'ethereum',
    description: 'Ethereum cryptocurrency',
    pollInterval: 300,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 'solana',
    name: 'Solana',
    category: 'crypto',
    emoji: '◎',
    source: 'coingecko',
    sourceId: 'solana',
    description: 'Solana cryptocurrency',
    pollInterval: 300,
    shieldEligible: true,
    perpEligible: true,
  },

  // ─── Forex ───
  {
    id: 'usd_inr',
    name: 'USD/INR',
    category: 'forex',
    emoji: '🇮🇳',
    source: 'coingecko_derived',
    sourceId: null,
    description: 'US Dollar to Indian Rupee exchange rate',
    pollInterval: 300,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 'eur_usd',
    name: 'EUR/USD',
    category: 'forex',
    emoji: '🇪🇺',
    source: 'coingecko_derived',
    sourceId: null,
    description: 'Euro to US Dollar exchange rate',
    pollInterval: 300,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 'gbp_usd',
    name: 'GBP/USD',
    category: 'forex',
    emoji: '🇬🇧',
    source: 'coingecko_derived',
    sourceId: null,
    description: 'British Pound to US Dollar exchange rate',
    pollInterval: 300,
    shieldEligible: true,
    perpEligible: true,
  },

  // ─── Real Estate (all via Parcl Labs) ───
  {
    id: 're_nyc',
    name: 'NYC Real Estate',
    category: 'real_estate',
    emoji: '🏙️',
    source: 'parcl',
    sourceId: 'NY-NYC',
    description: 'New York City price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_brooklyn',
    name: 'Brooklyn Real Estate',
    category: 'real_estate',
    emoji: '🌉',
    source: 'parcl',
    sourceId: 'NY-BRK',
    description: 'Brooklyn price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_miami',
    name: 'Miami Real Estate',
    category: 'real_estate',
    emoji: '🌴',
    source: 'parcl',
    sourceId: 'FL-MIA',
    description: 'Miami price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_miami_beach',
    name: 'Miami Beach Real Estate',
    category: 'real_estate',
    emoji: '🏖️',
    source: 'parcl',
    sourceId: 'FL-MB',
    description: 'Miami Beach price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_la',
    name: 'LA Real Estate',
    category: 'real_estate',
    emoji: '🌇',
    source: 'parcl',
    sourceId: 'CA-LA',
    description: 'Los Angeles price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_sf',
    name: 'San Francisco Real Estate',
    category: 'real_estate',
    emoji: '🌁',
    source: 'parcl',
    sourceId: 'CA-SF',
    description: 'San Francisco price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_sd',
    name: 'San Diego Real Estate',
    category: 'real_estate',
    emoji: '🏄',
    source: 'parcl',
    sourceId: 'CA-SD',
    description: 'San Diego price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_austin',
    name: 'Austin Real Estate',
    category: 'real_estate',
    emoji: '🤠',
    source: 'parcl',
    sourceId: 'TX-AUS',
    description: 'Austin TX price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_denver',
    name: 'Denver Real Estate',
    category: 'real_estate',
    emoji: '🏔️',
    source: 'parcl',
    sourceId: 'CO-DEN',
    description: 'Denver CO price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_atlanta',
    name: 'Atlanta Real Estate',
    category: 'real_estate',
    emoji: '🍑',
    source: 'parcl',
    sourceId: 'GA-ATL',
    description: 'Atlanta GA price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_chicago',
    name: 'Chicago Real Estate',
    category: 'real_estate',
    emoji: '🌬️',
    source: 'parcl',
    sourceId: 'IL-CHI',
    description: 'Chicago IL price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_boston',
    name: 'Boston Real Estate',
    category: 'real_estate',
    emoji: '🏛️',
    source: 'parcl',
    sourceId: 'MA-BOS',
    description: 'Boston MA price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_dc',
    name: 'Washington DC Real Estate',
    category: 'real_estate',
    emoji: '🏛️',
    source: 'parcl',
    sourceId: 'DC-WAS',
    description: 'Washington DC price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_vegas',
    name: 'Las Vegas Real Estate',
    category: 'real_estate',
    emoji: '🎰',
    source: 'parcl',
    sourceId: 'NV-LV',
    description: 'Las Vegas NV price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
  {
    id: 're_pittsburgh',
    name: 'Pittsburgh Real Estate',
    category: 'real_estate',
    emoji: '🏗️',
    source: 'parcl',
    sourceId: 'PA-PIT',
    description: 'Pittsburgh PA price per sqft',
    pollInterval: 3600,
    shieldEligible: true,
    perpEligible: true,
  },
];

module.exports = { MARKETS };
