let Agent = null;
let PinataStorageProvider = null;
let privateKeyToAccount = null;

let agent = null;
let initialized = false;

async function loadDeps() {
  const agentsMod = await import('@fileverse/agents');
  Agent = agentsMod.Agent;
  const storageMod = await import('@fileverse/agents/storage/index.js');
  PinataStorageProvider = storageMod.PinataStorageProvider;
  const viemMod = await import('viem/accounts');
  privateKeyToAccount = viemMod.privateKeyToAccount;
}

async function init() {
  const pinataJwt = process.env.PINATA_JWT;
  const pinataGateway = process.env.PINATA_GATEWAY;
  const pimlicoKey = process.env.PIMLICO_API_KEY;
  const privateKey = process.env.RELAYER_PRIVATE_KEY;

  if (!pinataJwt || !pinataGateway || !pimlicoKey || !privateKey) {
    console.warn('[Fileverse] Missing config (PINATA_JWT, PINATA_GATEWAY, PIMLICO_API_KEY) — skipping');
    return false;
  }

  try {
    await loadDeps();

    const storageProvider = new PinataStorageProvider({
      pinataJWT: pinataJwt,
      pinataGateway: pinataGateway,
    });

    const pk = privateKey.startsWith('0x') ? privateKey : `0x${privateKey}`;

    agent = new Agent({
      chain: 'sepolia',
      viemAccount: privateKeyToAccount(pk),
      pimlicoAPIKey: pimlicoKey,
      storageProvider,
    });

    await agent.setupStorage('aegis-shields');
    initialized = true;
    console.log('[Fileverse] Agent initialized — storage ready on IPFS + Sepolia');
    return true;
  } catch (error) {
    console.error('[Fileverse] Init error:', error.message);
    return false;
  }
}

/**
 * Create an on-chain shield document via Fileverse.
 * Returns { fileId, ipfsHash, portalUrl }
 */
async function createShieldDoc(shieldData) {
  if (!initialized || !agent) {
    console.warn('[Fileverse] Not initialized — cannot create doc');
    return null;
  }

  try {
    // Ensure all values are plain strings/numbers (no BigInt)
    const deposit = Number(shieldData.depositAmount) || 0;
    const entry = Number(shieldData.entryPrice) || 0;
    const budget = Number(shieldData.exposureBudget) || 0;
    const dur = Number(shieldData.durationMonths) || 0;
    const apy = Number(shieldData.yieldApy) || 0;

    const markdown = [
      '# Aegis Shield Agreement',
      '',
      '## Shield Details',
      `- **User**: ${String(shieldData.address)}`,
      `- **Asset**: ${String(shieldData.asset)}`,
      `- **Deposit**: $${deposit.toFixed(2)}`,
      `- **Duration**: ${dur} months`,
      `- **Entry Price**: $${entry.toFixed(2)}`,
      `- **Exposure Budget**: $${budget.toFixed(2)}`,
      `- **Yield Source**: ${String(shieldData.yieldSource || 'Best available')}`,
      `- **APY**: ${apy.toFixed(1)}%`,
      `- **Created**: ${new Date().toISOString()}`,
      '',
      '## Principal Protection Guarantee',
      `The deposited principal of $${deposit.toFixed(2)} is mathematically protected.`,
      `Only the yield-derived exposure budget of $${budget.toFixed(2)} is at risk.`,
      `Maximum loss = $0 on principal. Minimum return = $${deposit.toFixed(2)}.`,
      '',
      '## On-Chain References',
      `- **Chain**: Base Sepolia (84532)`,
      `- **Vault**: ${String(process.env.VAULT_CONTRACT_ADDRESS || 'N/A')}`,
      `- **A-USDC**: ${String(process.env.USDC_ADDRESS || 'N/A')}`,
      '',
      '---',
      '*This document is stored on IPFS via Fileverse and registered on-chain.*',
      '*Generated by Aegis Protocol*',
    ].join('\n');

    const file = await agent.create(markdown);
    // Safe stringify (handles BigInt)
    const safeStringify = (obj) => JSON.stringify(obj, (_, v) => typeof v === 'bigint' ? v.toString() : v, 2);
    console.log(`[Fileverse] Shield doc created — full response:`, safeStringify(file));

    const fileId = String(file?.fileId ?? file?.id ?? '');
    const txHash = String(file?.hash ?? '');

    return {
      fileId,
      txHash,
      portalUrl: `https://agents.fileverse.io`,
    };
  } catch (error) {
    console.error('[Fileverse] Error creating doc:', error.message);
    return null;
  }
}

function isInitialized() {
  return initialized;
}

module.exports = { init, createShieldDoc, isInitialized };
